// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia.Data;

#nullable disable

namespace Persistencia.Data.Migrations
{
    [DbContext(typeof(DbAppContext))]
    [Migration("20240501214008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entities.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCandidato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CiudadRecidencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("CiudadRecidencia");

                    b.Property<string>("DescripcionHabilidades")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("DescripcionHabilidades");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<string>("Experiencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Experiencia");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("DateTime")
                        .HasColumnName("FechaNacimiento");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Genero");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar")
                        .HasColumnName("Telefono");

                    b.Property<string>("UrlLinkedIn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("UrlLinkedIn");

                    b.HasKey("Id");

                    b.ToTable("Candidato", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CiudadRecidencia = "Bogotá",
                            DescripcionHabilidades = "Desarrollo de software",
                            Email = "juan@example.com",
                            Experiencia = "5 años",
                            FechaNacimiento = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "Juan Pérez",
                            Telefono = "123456789",
                            UrlLinkedIn = "https://www.linkedin.com/in/juanperez"
                        },
                        new
                        {
                            Id = 2,
                            CiudadRecidencia = "Medellín",
                            DescripcionHabilidades = "Gestión de proyectos",
                            Email = "maria@example.com",
                            Experiencia = "8 años",
                            FechaNacimiento = new DateTime(1985, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "María López",
                            Telefono = "987654321",
                            UrlLinkedIn = "https://www.linkedin.com/in/marialopez"
                        },
                        new
                        {
                            Id = 3,
                            CiudadRecidencia = "Cali",
                            DescripcionHabilidades = "Diseño gráfico",
                            Email = "alex@example.com",
                            Experiencia = "3 años",
                            FechaNacimiento = new DateTime(1988, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Otro",
                            NombreCompleto = "Alex García",
                            Telefono = "456789123",
                            UrlLinkedIn = "https://www.linkedin.com/in/alexgarcia"
                        },
                        new
                        {
                            Id = 4,
                            CiudadRecidencia = "Barranquilla",
                            DescripcionHabilidades = "Marketing digital",
                            Email = "ana@example.com",
                            Experiencia = "6 años",
                            FechaNacimiento = new DateTime(1992, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Ana Torres",
                            Telefono = "741852963",
                            UrlLinkedIn = "https://www.linkedin.com/in/anatorres"
                        },
                        new
                        {
                            Id = 5,
                            CiudadRecidencia = "Cartagena",
                            DescripcionHabilidades = "Desarrollo web",
                            Email = "david@example.com",
                            Experiencia = "7 años",
                            FechaNacimiento = new DateTime(1987, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "David Martínez",
                            Telefono = "369258147",
                            UrlLinkedIn = "https://www.linkedin.com/in/davidmartinez"
                        },
                        new
                        {
                            Id = 6,
                            CiudadRecidencia = "Bucaramanga",
                            DescripcionHabilidades = "Diseño UX/UI",
                            Email = "laura@example.com",
                            Experiencia = "4 años",
                            FechaNacimiento = new DateTime(1993, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Laura Ramírez",
                            Telefono = "654987321",
                            UrlLinkedIn = "https://www.linkedin.com/in/lauraramirez"
                        },
                        new
                        {
                            Id = 7,
                            CiudadRecidencia = "Santa Marta",
                            DescripcionHabilidades = "Administración de bases de datos",
                            Email = "diego@example.com",
                            Experiencia = "9 años",
                            FechaNacimiento = new DateTime(1984, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "Diego Sánchez",
                            Telefono = "852369741",
                            UrlLinkedIn = "https://www.linkedin.com/in/diegosanchez"
                        },
                        new
                        {
                            Id = 8,
                            CiudadRecidencia = "Cúcuta",
                            DescripcionHabilidades = "Desarrollo móvil",
                            Email = "carolina@example.com",
                            Experiencia = "6 años",
                            FechaNacimiento = new DateTime(1991, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Carolina Martín",
                            Telefono = "987123654",
                            UrlLinkedIn = "https://www.linkedin.com/in/carolinamartin"
                        },
                        new
                        {
                            Id = 9,
                            CiudadRecidencia = "Pereira",
                            DescripcionHabilidades = "Gestión de proyectos",
                            Email = "javier@example.com",
                            Experiencia = "7 años",
                            FechaNacimiento = new DateTime(1989, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "Javier Fernández",
                            Telefono = "369741852",
                            UrlLinkedIn = "https://www.linkedin.com/in/javierfernandez"
                        },
                        new
                        {
                            Id = 10,
                            CiudadRecidencia = "Manizales",
                            DescripcionHabilidades = "Desarrollo de aplicaciones móviles",
                            Email = "valentina@example.com",
                            Experiencia = "3 años",
                            FechaNacimiento = new DateTime(1995, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Valentina Ruiz",
                            Telefono = "258147369",
                            UrlLinkedIn = "https://www.linkedin.com/in/valentinaruiz"
                        },
                        new
                        {
                            Id = 11,
                            CiudadRecidencia = "Bogotá",
                            DescripcionHabilidades = "Análisis de datos",
                            Email = "gabriel@example.com",
                            Experiencia = "5 años",
                            FechaNacimiento = new DateTime(1987, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "Gabriel Gómez",
                            Telefono = "147258369",
                            UrlLinkedIn = "https://www.linkedin.com/in/gabrielgomez"
                        },
                        new
                        {
                            Id = 12,
                            CiudadRecidencia = "Medellín",
                            DescripcionHabilidades = "Marketing digital",
                            Email = "paula@example.com",
                            Experiencia = "4 años",
                            FechaNacimiento = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Paula Herrera",
                            Telefono = "123789456",
                            UrlLinkedIn = "https://www.linkedin.com/in/paulaherrera"
                        },
                        new
                        {
                            Id = 13,
                            CiudadRecidencia = "Cali",
                            DescripcionHabilidades = "Desarrollo web",
                            Email = "alejandro@example.com",
                            Experiencia = "8 años",
                            FechaNacimiento = new DateTime(1986, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "Alejandro Torres",
                            Telefono = "987654321",
                            UrlLinkedIn = "https://www.linkedin.com/in/alejandrotorres"
                        },
                        new
                        {
                            Id = 14,
                            CiudadRecidencia = "Barranquilla",
                            DescripcionHabilidades = "Diseño gráfico",
                            Email = "natalia@example.com",
                            Experiencia = "3 años",
                            FechaNacimiento = new DateTime(1994, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Natalia Díaz",
                            Telefono = "369852147",
                            UrlLinkedIn = "https://www.linkedin.com/in/nataliadiaz"
                        },
                        new
                        {
                            Id = 15,
                            CiudadRecidencia = "Cartagena",
                            DescripcionHabilidades = "Administración de sistemas",
                            Email = "andres@example.com",
                            Experiencia = "10 años",
                            FechaNacimiento = new DateTime(1983, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "Andrés López",
                            Telefono = "741258963",
                            UrlLinkedIn = "https://www.linkedin.com/in/andreslopez"
                        },
                        new
                        {
                            Id = 16,
                            CiudadRecidencia = "Bucaramanga",
                            DescripcionHabilidades = "Desarrollo de software",
                            Email = "sofia@example.com",
                            Experiencia = "6 años",
                            FechaNacimiento = new DateTime(1993, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Sofía García",
                            Telefono = "852369741",
                            UrlLinkedIn = "https://www.linkedin.com/in/sofiagarcia"
                        },
                        new
                        {
                            Id = 17,
                            CiudadRecidencia = "Santa Marta",
                            DescripcionHabilidades = "Gestión de proyectos",
                            Email = "carlos@example.com",
                            Experiencia = "7 años",
                            FechaNacimiento = new DateTime(1988, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "Carlos Hernández",
                            Telefono = "123456789",
                            UrlLinkedIn = "https://www.linkedin.com/in/carloshernandez"
                        },
                        new
                        {
                            Id = 18,
                            CiudadRecidencia = "Cúcuta",
                            DescripcionHabilidades = "Diseño UX/UI",
                            Email = "isabella@example.com",
                            Experiencia = "5 años",
                            FechaNacimiento = new DateTime(1990, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Isabella Martínez",
                            Telefono = "987654321",
                            UrlLinkedIn = "https://www.linkedin.com/in/isabellamartinez"
                        },
                        new
                        {
                            Id = 19,
                            CiudadRecidencia = "Pereira",
                            DescripcionHabilidades = "Desarrollo móvil",
                            Email = "miguel@example.com",
                            Experiencia = "8 años",
                            FechaNacimiento = new DateTime(1985, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "Miguel Rodríguez",
                            Telefono = "369258147",
                            UrlLinkedIn = "https://www.linkedin.com/in/miguelrodriguez"
                        },
                        new
                        {
                            Id = 20,
                            CiudadRecidencia = "Manizales",
                            DescripcionHabilidades = "Marketing digital",
                            Email = "valeria@example.com",
                            Experiencia = "6 años",
                            FechaNacimiento = new DateTime(1992, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Valeria López",
                            Telefono = "741852963",
                            UrlLinkedIn = "https://www.linkedin.com/in/valerialopez"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Generic.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRefreshToken");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Generic.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRol")
                        .HasAnnotation("MysqlValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Gerente"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Empleado"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Cliente"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Generic.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario")
                        .HasAnnotation("MysqlValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "britodelgado514@gmail.com",
                            Password = "123456",
                            UserName = "Sicer Brito"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Generic.UsuarioRoles", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("Dominio.Entities.Generic.RefreshToken", b =>
                {
                    b.HasOne("Dominio.Entities.Generic.Usuario", "Usuarios")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Dominio.Entities.Generic.UsuarioRoles", b =>
                {
                    b.HasOne("Dominio.Entities.Generic.Rol", "Roles")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Generic.Usuario", "Usuarios")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Dominio.Entities.Generic.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Dominio.Entities.Generic.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
